const EVENTS = {
    STUDENT_ADDED: 'STUDENT_ADDED',
    STUDENT_REMOVED: 'STUDENT_REMOVED',
    DATA_LOADED: 'DATA_LOADED',
    DATA_SAVED: 'DATA_SAVED',
    BACKUP_CREATED: 'BACKUP_CREATED',
    BACKUP_FAILED: 'BACKUP_FAILED',
};

module.exports = EVENTS;
